name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-dotnet:
    name: Build and Test C#
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build C# code
        run: dotnet build

      - name: Run C# tests
        run: dotnet test

  build-typescript:
    name: Build and Test TypeScript
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (TypeScript project)
        run: npm install
        working-directory: DotnetTemplate.Web

      - name: Build TypeScript code
        run: npm run build
        working-directory: DotnetTemplate.Web

      - name: Lint TypeScript code
        run: npm run lint
        working-directory: DotnetTemplate.Web

      - name: Run TypeScript tests
        run: npm run test
        working-directory: DotnetTemplate.Web

  notify-slack:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: [build-dotnet, build-typescript]
    if: always()

    steps:
      - name: Send Slack notification
        run: |
          # Determine overall status based on needs
          if [[ "${{ needs.build-dotnet.result }}" == "success" && "${{ needs.build-typescript.result }}" == "success" ]]; then
            STATUS_TEXT="✅ Workflow succeeded"
          elif [[ "${{ needs.build-dotnet.result }}" == "cancelled" || "${{ needs.build-typescript.result }}" == "cancelled" ]]; then
            STATUS_TEXT="⚠️ Workflow was cancelled"
          else
            STATUS_TEXT="❌ Workflow failed"
          fi

          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"$STATUS_TEXT for *${{ github.repository }}* on branch *${{ github.ref_name }}*.\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow>\"}" \
          "${{ secrets.SLACK_WEBHOOK_URL }}"
